export const envConfig = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_MEMBER_LOGIN: process.env.NEXT_PUBLIC_MEMBER_LOGIN,
  NEXT_PUBLIC_MEMBER_REGISTER: process.env.NEXT_PUBLIC_MEMBER_REGISTER,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
  NEXT_PUBLIC_VBG_API_KEY: NEXT_PUBLIC_VBG_API_KEY,
  NEXT_PUBLIC_VBG_API_URL: process.env.NEXT_PUBLIC_VBG_API_URL,
};